### ISSUE TITLE
9.0.5.5 causing errors upon logging in.

### ISSUE THREAD

**Issue by Ookami313** [Torhal/Broker_Currency#1]
Updated to 9.0.5.5 and I receive the following errors when I log into the game.

1x Broker_Currency\Broker_Currency-9.0.5.5.lua:12: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceBucket-3.0".
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:189: in function `EmbedLibrary'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:171: in function `EmbedLibraries'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:138: in function `NewAddon'
[string "@Broker_Currency\Broker_Currency-9.0.5.5.lua"]:12: in main chunk

Locals:
(*temporary) = "Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceBucket-3.0"."

1x Broker_Currency\Tooltip.lua:60: table index is nil
[string "@Broker_Currency\Tooltip.lua"]:60: in main chunk

Locals:
AddOnFolderName = "Broker_Currency"
private = <table> {
 CurrencyItemID = <table> {
 }
 CurrencyItemName = <table> {
 }
 CurrencyID = <table> {
 }
 CategoryCurrencyIDs = <table> {
 }
 Debug = <function> defined @Broker_Currency\Debugger.lua:22
 ExpansionCurrencyIDs = <table> {
 }
 ExpansionCurrencyGroups = <table> {
 }
 IgnoredCurrencyIDs = <table> {
 }
 CurrencyName = <table> {
 }
 GetDebugger = <function> defined @Broker_Currency\Debugger.lua:16
 CategoryCurrencyGroups = <table> {
 }
}
LibStub = <table> {
 NewLibrary = <function> defined @AchieveIt\libs\LibStub\LibStub.lua:20
 minors = <table> {
 }
 minor = 2
 IterateLibraries = <function> defined @AchieveIt\libs\LibStub\LibStub.lua:46
 GetLibrary = <function> defined @AchieveIt\libs\LibStub\LibStub.lua:36
 libs = <table> {
 }
}
AceConfigDialog = <table> {
 ConfigTableChanged = <function> defined @Altoholic\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1829
 CloseAll = <function> defined @Altoholic\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1810
 Close = <function> defined @Altoholic\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1820
 SetDefaultSize = <function> defined @Altoholic\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1840
 tooltip = AceConfigDialogTooltip {
 }
 Open = <function> defined @Altoholic\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1855
 AddToBlizOptions = <function> defined @Altoholic\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1986
 BlizOptions = <table> {
 }
 popup = <unnamed> {
 }
 GetStatusTable = <function> defined @Altoholic\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:407
 OpenFrames = <table> {
 }
 Status = <table> {
 }
 frame = <unnamed> {
 }
 FeedGroup = <function> defined @Altoholic\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1600
 SelectGroup = <function> defined @Altoholic\libs\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:437
}
LibDataBroker = <table> {
 attributestorage = <table> {
 }
 pairs = <function> defined @AllTheThings\lib\LibDataBroker-1.1\LibDataBroker-1.1.lua:70
 NewDataObject = <function> defined @AllTheThings\lib\LibDataBroker-1.1\LibDataBroker-1.1.lua:36
 callbacks = <table> {
 }
 ipairs = <function> defined @AllTheThings\lib\LibDataBroker-1.1\LibDataBroker-1.1.lua:81
 RegisterCallback = <function> defined @AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetNameByDataObject = <function> defined @AllTheThings\lib\LibDataBroker-1.1\LibDataBroker-1.1.lua:63
 GetDataObjectByName = <function> defined @AllTheThings\lib\LibDataBroker-1.1\LibDataBroker-1.1.lua:59
 UnregisterCallback = <function> defined @AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 domt = <table> {
 }
 proxystorage = <table> {
 }
 DataObjectIterator = <function> defined @AllTheThings\lib\LibDataBroker-1.1\LibDataBroker-1.1.lua:55
 namestorage = <table> {
 }
 UnregisterAllCallbacks = <function> defined @AchieveIt\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
}
LibQTip = <table> {
 activeTooltips = <table> {
 }
 LabelPrototype = <table> {
 }
 tooltipHeap = <table> {
 }
 cellPrototype = <table> {
 }
 tableHeap = <table> {
 }
 providerMetatable = <table> {
 }
 timerHeap = <table> {
 }
 providerPrototype = <table> {
 }
 onReleaseHandlers = <table> {
 }
 LabelProvider = <table> {
 }
 tipMetatable = <table> {
 }
 frameHeap = <table> {
 }
 IterateTooltips = <function> defined @Broker_Currency\Libraries\LibQTip-1.0\LibQTip-1.0.lua:167
 CreateCellProvider = <function> defined @Broker_Currency\Libraries\LibQTip-1.0\LibQTip-1.0.lua:284
 layoutCleaner = <unnamed>

**Comment by Torhal** [comment]
Fixed in 9.0.5.6.
