### ISSUE TITLE
Update??

### ISSUE THREAD

**Issue by Wraithlord2015** [Torhal/Broker_Currency#12]
Is there any sort of update from the author, or does anyone have a self developed update that fixes the issues with the addon (version 9.0.5.7)??

**Comment by TreizeEU** [comment]
Several months and still no word to my ticket as well. 

In the meantime, what I've done was to downgrade to version 9.0.2.1 and manually added Shadowlands currencies myself to the Currencies.lua file (uploading my current edit of that file here below, with 9.1 currencies taken from wowhead).

[Currencies.zip](https://github.com/Torhal/Broker_Currency/files/6735084/Currencies.zip)

**Comment by Wraithlord2015** [comment]
I did the same thing as well. I was hoping that I wouldn't have to revert. I like how the different currencies are broken up by expansion; pvp & holidays/special events. I don't want to have to go through and edit the LUA to make it so it's using the same sorting method, but with 9.0.2 instead of the most recent version.

________________________________
