### ISSUE TITLE
LUA Error in Broker_Currency: attempt to index local 'left4' (a nil value)

### ISSUE THREAD

**Issue by amethystnw** [Torhal/Broker_Currency#14]
I'm getting the following LUA error when logging into the game in Shadowlands.  I have current release ver 9.0.5.7 installed. 

Message: Interface\AddOns\Broker_Currency\Broker_Currency.lua:265: attempt to index local 'left4' (a nil value)
Time: Tue Aug  3 19:25:04 2021
Count: 1
Stack: Interface\AddOns\Broker_Currency\Broker_Currency.lua:265: attempt to index local 'left4' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Broker_Currency\Broker_Currency.lua"]:265: in function <Interface\AddOns\Broker_Currency\Broker_Currency.lua:245>
[string "@Interface\AddOns\Broker_Currency\Broker_Currency.lua"]:630: in function <Interface\AddOns\Broker_Currency\Broker_Currency.lua:627>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:623: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

**Comment by amethystnw** [comment]
I see this error is corrected by the code left by @christophknuth.  After the edit, the LUA error doesn't appear.

**Comment by rhodan412** [comment]
How did you fix this error?  I couldn't find the coding left by @christophknuth
