### ISSUE TITLE
Gold Summary Blanking Out - No LUA Errors

### ISSUE THREAD

**Issue by rhodan412** [Torhal/Broker_Currency#15]
I have made updates per https://github.com/Torhal/Broker_Currency/pull/13, however, am only able to see the character gold for two of my toons under the Summary tooltip (these toons are the one I'm currently on and the first toon that I logged into when changes were made on the above fix).

**Comment by Aes-Seda** [comment]
I also did the #13. and am still having .lua errors especially if I time out.
