### ISSUE TITLE
WOTLK Classic support?

### ISSUE THREAD

**Issue by Jakobud** [Torhal/Broker_Currency#18]
WOTLK Classic introduced currencies. Is it possible to get support for this?

Alternatively can anyone tell me what currencies were used in WOTLK? I think it's these:

- Honor
- Arena Points
- DalaranJewelcraftersToken 
- ChampionsSeal
- Badge of Justice
- Emblem of Heroism
- Emblem of Valor

Any others?

Side note, why are some of these "ignored" in the addon? Where they not used in later expansions at all?

Also some TBC items I guess do those later become currency? Stuff like Halaa Research Tokens. The addon shows them as being currency at one point but in WOTLK classic at the moment they are still items in your bags.

**Comment by PJai** [comment]
@Jakobud I am using Version 9.0.2.1 from Curse (https://github.com/Torhal/Broker_Currency/issues/16#issuecomment-991729364) plus a modified currency file.
[Currencies.zip](https://github.com/Torhal/Broker_Currency/files/9640238/Currencies.zip)

![grafik](https://user-images.githubusercontent.com/22389964/192133465-21bee5e4-7e09-4647-a7d0-c93ad708e4ea.png)

**Comment by TreizeEU** [comment]
I will update that file under the other ticket, with currencies for Dragonflight once it's released, when I know which ones are actually used. Previously, I've just added new currencies from Wowhead's database and piled them on at the bottom of "CURRENCY_IDS_BY_NAME" (starting at line and 14) as well as the "MISCELLANEOUS_CURRENCY_IDS" category.

As for TBC currencies like the Halaa-related ones. Those are still items in your bag, so they'll be under "ITEM_CURRENCY_IDS_BY_NAME" (starting around line 120?).

**Comment by rhodan412** [comment]
All I get on the broker bar is "Initializing" and the following error:

Message: Interface\AddOns\Broker_Currency\Broker_Currency.lua:799: Usage: local info = C_CurrencyInfo.GetCurrencyInfo(type)
Time: Fri Nov  4 11:15:50 2022
Count: 1
Stack: Interface\AddOns\Broker_Currency\Broker_Currency.lua:799: Usage: local info = C_CurrencyInfo.GetCurrencyInfo(type)
[string "=[C]"]: in function `GetCurrencyInfo'
[string "@Interface\AddOns\Broker_Currency\Broker_Currency.lua"]:799: in function `func'
[string "@Interface\AddOns\Broker_Currency\libs\AceTimer-3.0\AceTimer-3.0.lua"]:57: in function <...s\Broker_Currency\libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals: (*temporary) = nil

[PJai](https://github.com/PJai), Could you provide the full file of your functional Broker Currency?  It might be the encouragement needed for Torhal to update the addon?

**Comment by TreizeEU** [comment]
@rhodan412 It is an older version (9.0.2.1) with a modified Currency.lua that I keep updating and uploading to the other ticket. I've done no other changes to it. I don't know alot of lua coding, but I can add new currencies to that file. :)

**Comment by TreizeEU** [comment]
@rhodan412 
@PJai 
I've uploaded my current version of this addon under ticket #16 , with entire folder this time. :)

**Comment by BujuArena** [comment]
I have submitted a pull request (#22) which adds support for Cataclysm Classic.
