### ISSUE TITLE
9.0.5.7 - Summary only displaying Gold

### ISSUE THREAD

**Issue by voidzone** [Torhal/Broker_Currency#4]
Summary's only displaying gold regardless of the other items selected.

No Lua errors.

**Comment by TreizeEU** [comment]
@layzsmurf 

I don't use that addon and still have issues with the summary (see my other ticket #3 ).

**Comment by Nota797** [comment]
Also on 9.0.5.7 with this issue. The summary can show gold, silver, and copper, but that's it.
I do not use Broker_Currencyflow.

**Comment by Wraithlord2015** [comment]
Just wanted to post an update. Under the pull requests - christophknuth posted a fix that allows the latest version of the addon to be used. I'm currently using it and haven't had any errors thus far.
