### ISSUE TITLE
9.0.5.7 LUA errors

### ISSUE THREAD

**Issue by Hurrok** [Torhal/Broker_Currency#5]
First char to log in is fine. Switching to another char gives LUA errors in Broker_currency.lua:

always:
line 265: attempt to index local 'left4' (a nil value)

one of these (depends on which char is logged in first):
line 352: attempt to index local 'playerInfo' (a nil value)
line 376: attempt to compare nil with number

**Comment by kemayo** [comment]
It's not just entirely switching characters -- logging back in as the same character also triggers it.

**Comment by kemayo** [comment]
Oh, and reloading the UI once you're logged in will eventually make it stop erroring.

**Comment by Fringetastic** [comment]
I accidentally reinstalled the latest version and I got the errors on load and reload. Going back to working version.

**Comment by Wraithlord2015** [comment]
Tried reloading the UI numerous times; it doesn't work for everyone. Eventually the addon hits a point where it just shows gold and then starts blanking out the information.

**Comment by christophknuth** [comment]
I've create #13 which fixes the issue for me.

**Comment by Wraithlord2015** [comment]
Just wanted to post an update. Under the pull requests - christophknuth posted a fix that allows the latest version of the addon to be used. I'm currently using it and haven't had any errors thus far.
