### ISSUE TITLE
errors with latest version

### ISSUE THREAD

**Issue by Addonman** [Torhal/Broker_Currency#7]
Error occured in: Global
Count: 1
Message: ..\AddOns\Broker_Currency\Tooltip.lua line 180:
   attempt to index local 'gainedReference' (a nil value)
Debug:
   [string "@RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149:
      ...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147
   [string "=[C]"]: ?
   [string "@Broker_Currency\Tooltip.lua"]:180:
      Broker_Currency\Tooltip.lua:177
   [string "@Broker_Currency\Tooltip.lua"]:216:
      Broker_Currency\Tooltip.lua:184
   [string "@Broker_Currency\Tooltip.lua"]:274: OnEnter()
   [string "@Bazooka\Bazooka.lua"]:1583: showTip()
   [string "@Bazooka\Bazooka.lua"]:1388:
      Bazooka\Bazooka.lua:1379
Locals:
private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:48
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:90
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:110
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:86
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:119
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:80
 NewError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:52
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:97
}
orig_errorhandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717

Count: 11
Message: ..\AddOns\Broker_Currency\Broker_Currency.lua line 376:
   attempt to compare nil with number
Debug:
   [string "@RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149:
      ...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147
   [string "=(tail call)"]: ?
   [string "@Broker_Currency\Broker_Currency.lua"]:376: ?()
   [string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [string "=[C]"]: ?
   [string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   [string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: Fire()
   [string "@Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:120:
      Ace3\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None

Count: 1
Message: ..\AddOns\Broker_Currency\Broker_Currency.lua line 265:
   attempt to index local 'left4' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "@Broker_Currency\Broker_Currency.lua"]:265:
      Broker_Currency\Broker_Currency.lua:245
   [string "@Broker_Currency\Broker_Currency.lua"]:630:
      Broker_Currency\Broker_Currency.lua:627
   [string "=[C]"]: ?
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:65
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:498: InitializeAddon()
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:623:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:615
Locals:
None

**Comment by KyrosKrane** [comment]
I can confirm these are still happening on 9.0.5.7. I've had to roll back to 9.0.2.1.

**Comment by Wraithlord2015** [comment]
Having the same issues that have been reported by many others. Having backed up my files, tried deleting & installing fresh copies of each version. Seems like 9.0.2.1 is the most recent version that doesn't blow up and start throwing tons of errors.

**Comment by Wraithlord2015** [comment]
Just wanted to post an update. Under the pull requests - christophknuth posted a fix that allows the latest version of the addon to be used. I'm currently using it and haven't had any errors thus far.

**Comment by KyrosKrane** [comment]
The lua error is fixed in pull #13 as Wraithlord noted. But it doesn't fix the underlying problem of no currencies in the mouseover summary list.

**Comment by Wraithlord2015** [comment]
Initially when I posted - it wasn't exhibiting that behavior. When I logged back in just a few minutes ago - no currencies are showing in the mouseover summary list (as stated above). Label me annoyed - I thought it was finally fixed.
